apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-shipping-monitor
  labels:
    app: monitor-app
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: monitor-app
  template:
    metadata:
      labels:
        app: monitor-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"  # Adjust the port to your needs
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: monitor-app
        image: index.docker.io/eugeniaakpo/monitor:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Expose the port where your monitor is running internally
        resources:
          requests:
            cpu: 200m
        command:
          - "python"
        args:
          - "monitor.py"
          - "--service1=frontend"
          - "--service2=shippingservice"
          - "--training_data_file=boutique_training.json"
          - "--prometheus_port=8080"
