apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-detector
  labels:
    app: incident-app
spec:
  replicas: 1  # Set the desired number of replicas
  selector:
    matchLabels:
      app: incident-app
  template:
    metadata:
      labels:
        app: incident-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"  # Adjust the port to your needs
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: incident-app
        image: eugeniaakpo/incident-detector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083  # Expose the port where your incident detector is running internally
        resources:
          requests:
            cpu: 200m
        command:
          - "python"
        args:
          - "incident.py"
      
