apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name  : paymentservice-fault-injection
spec:
  hosts:
  - paymentservice
  http:
  - fault:
      delay:
        fixedDelay: .2s
        percent: 100
    match:
    - sourceLabels:
        app: checkoutservice
    route:
    - destination:
        host: paymentservice

  - fault:
      delay:
        percent: 100
        fixedDelay: .2s
    match:
    - uri:
        regex: ".*/GetQuote"
    route:
    - destination:
        host: paymentservice

  - route:
    - destination:
        host: paymentservice  


