apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name  : cartservice-fault-injection
spec:
  hosts:
  - cartservice
  http:
  - fault:
      delay:
        fixedDelay: .2s
        percent: 100
    match:
    - sourceLabels:
        app: frontend
    route:
    - destination:
        host: cartservice

  - fault:
      delay:
        percent: 100
        fixedDelay: .2s
    match:
    - uri:
        regex: ".*/GetQuote"
    route:
    - destination:
        host: cartservice

  - route:
    - destination:
        host: cartservice  


